server:
 port: 9000
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
   driverClassName: com.mysql.cj.jdbc.Driver
   username: root
   password: Vilas@123
 h2:
  console:
   enabled: true
 jpa:
   properties: 
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   hibernate:
     ddl-auto: update
   show-sql: true

